CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);



CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(2000) NOT NULL ,
    category_id BIGINT NOT NULL ,
    confirmed_requests INTEGER,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL ,
    description VARCHAR(7000),
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL ,
    initiator_id BIGINT NOT NULL ,
    location_lat FLOAT4 NOT NULL ,
    location_lon FLOAT4 NOT NULL ,
    paid BOOLEAN NOT NULL ,
    participant_limit INTEGER,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state VARCHAR(255) NOT NULL ,
    title VARCHAR(120) NOT NULL ,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS participation_requests(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP NOT NULL ,
    event BIGINT NOT NULL,
    requester BIGINT NOT NULL,
    status VARCHAR(20),
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_event FOREIGN KEY (event) REFERENCES events(id),
    CONSTRAINT fk_requester FOREIGN KEY (requester) REFERENCES users(id),
    CONSTRAINT UQ_PARTICIPANT_PER_EVENT UNIQUE (requester, event)
);

CREATE TABLE IF NOT EXISTS compilations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN NOT NULL,
    title VARCHAR(255),
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilations (
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, compilation_id)
);